#!/usr/bin/python3.8

import sys
import json

def show_help():
    print("Takes a file generated by")
    print("\tcargo +nightly bench -- --format=json -Z unstable-options")
    print("and generates a .csv file")
    print("Usage: " + sys.argv[0] + " input_file output_file")

def main():
    if len(sys.argv) != 3:
        show_help()
        exit(-1)

    csv_data = []
    input_file = sys.argv[1]
    with open(input_file) as f:
        lines = f.readlines()
        for line in lines:
            parse_line(line, csv_data)

    output_file = sys.argv[2]
    export_csv(csv_data, output_file)

def parse_line(line, csv_output):
    line_dict = json.loads(line)

    if line_dict['type'] == 'bench':
        line_csv = bench_json_to_csv(line_dict)
        csv_output.append(line_csv)

def bench_json_to_csv(data):
    line_csv = data['name'] + ',';
    line_csv = line_csv + str(data['median']) + ',';
    line_csv = line_csv + str(data['deviation']) + '\n'

    return line_csv

def export_csv(csv_data, output_filename):
    with open(output_filename, 'w') as f:
        f.write('name,median,deviation\n')

        for line in csv_data:
            f.write(line)


if __name__ == '__main__':
    main()